motorcycles = ['yamaha', 'honda', 'harley davidson', 'honda', 'honda', 'tesla', 'honda', 'california', 'ford']
print(motorcycles)
popped_motorcycle = motorcycles.pop()
print(motorcycles)
print(popped_motorcycle)
motorcycle_count = motorcycles.__len__()
print(motorcycle_count)
motorcycles.insert(0, 'ducati')
print(motorcycles)
motorcycle_count = motorcycles.__len__()
print(motorcycle_count)
del motorcycles[1]
print(motorcycles)
last_owned = motorcycles.pop()
print(f'The last motorcycle I owned was a {last_owned.title()}')
print(motorcycles)
another_owned = motorcycles.pop()
print(f'Another motorcycle that I owned, was a {another_owned.title()}')
print(motorcycles)
wish_tesla = motorcycles.pop()
print(f'One company that I wish would produce a motorcycle is {wish_tesla.title()}')
motorcycle_count = motorcycles.__len__()
print(motorcycle_count)
motorcycles.remove('honda')
print(motorcycles)
too_expensive = 'harley davidson'
print(f"\nA {too_expensive.title()} is way overpriced for what you get in that bike!!!")
